### ISSUE TITLE
[Question] Publishing on Modrinth and further developmen

### ISSUE THREAD

**Issue by Felix14-v2** [tildejustin/pretty-hitboxes#1]
Thanks for updating the mod! Do you have any plans to release your fork on Modrinth and keep updating it? The MIT license allows you to do so.

**Comment by tildejustin** [comment]
the modrinth people didn't like when i tried to publish a fork there last time, so i'm not inclined to try again...that being said i don't have a problem with updating this, i just probably won't remember unless someone makes an issue b/c i don't really have the time to maintain everything for every update
